// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWoxXla-EbKuQicw6nj6bhO2Pf_LsH5sY',
    appId: '1:687104936130:web:220bfe84ba3b436ec0935b',
    messagingSenderId: '687104936130',
    projectId: 'saga-marketplace-f4811',
    authDomain: 'saga-marketplace-f4811.firebaseapp.com',
    storageBucket: 'saga-marketplace-f4811.firebasestorage.app',
    measurementId: 'G-BVLBE6N2FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNnIxHGvHgdpCPe-GGA6xE85Hv8D1HfyY',
    appId: '1:687104936130:android:0bf234f0030e4d71c0935b',
    messagingSenderId: '687104936130',
    projectId: 'saga-marketplace-f4811',
    storageBucket: 'saga-marketplace-f4811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBnTHazUrojaQ6PTGs72YGZqxHG_IQo8',
    appId: '1:687104936130:ios:4b82e097a77218e8c0935b',
    messagingSenderId: '687104936130',
    projectId: 'saga-marketplace-f4811',
    storageBucket: 'saga-marketplace-f4811.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRBnTHazUrojaQ6PTGs72YGZqxHG_IQo8',
    appId: '1:687104936130:ios:4b82e097a77218e8c0935b',
    messagingSenderId: '687104936130',
    projectId: 'saga-marketplace-f4811',
    storageBucket: 'saga-marketplace-f4811.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWoxXla-EbKuQicw6nj6bhO2Pf_LsH5sY',
    appId: '1:687104936130:web:72287cd3753bdbdbc0935b',
    messagingSenderId: '687104936130',
    projectId: 'saga-marketplace-f4811',
    authDomain: 'saga-marketplace-f4811.firebaseapp.com',
    storageBucket: 'saga-marketplace-f4811.firebasestorage.app',
    measurementId: 'G-2GWFSM4JQ6',
  );
}
